# Generated by Django 5.0 on 2024-01-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peyk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='No',
            new_name='tracking_code',
        ),
    ]
